--Drope the old tables
DROP TABLE word_counts;
DROP TABLE files;

-- Create the input table
CREATE TABLE files(line STRING);

--load data into the file
LOAD DATA LOCAL INPATH '/root/input.txt' INTO TABLE files;

--Perform MapReduce
CREATE TABLE word_counts AS
SELECT word, count(word) AS totalCount FROM
(SELECT explode(split(line, ' ')) AS word FROM files) w
GROUP BY word
ORDER BY totalCount;

--Print output
SELECT * FROM word_counts;
